### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Chiroyce1** [gosoccerboy5/flask-chat-app#1]
I would've PR'd all of this (except #5) but I decided it was best if you learnt to do it on your own :)

1. Delete the `venv/` directory and add it to `.gitignore`. It's basically the `node_modules` for Python (it also includes the Python runtime itself), and you committed it all to GitHub 💀

2. use [bcrypt](https://pypi.org/project/bcrypt/) instead of SHA256 to hash passwords, SHA256 is not at all suitable for hashing passwords. bcrypt will also provide [salting](https://en.wikipedia.org/wiki/Salt_(cryptography)) for more security 💪🏻

3. A random port isn't really required, `8080` is best for running on replit or locally. also maybe use `debug=True` if you're running it for development purposes, it will make debugging errors a lot easier
```python
if __name__ == "__main__":
    app.run(host='0.0.0.0', port=8080, debug=True)
```

4. Use [Context Managers](https://realpython.com/python-with-statement/) for reading/writing files
```python
# Instead of
write_file = open("user_data.json", "w")
write_file.write(json.dumps(all_user_data))
write_file.close()

# Use the below
with open("user_data.json", "w") as file:
    file.write(json.dumps(all_user_data))
    # Using a context manager automatically closes files even if an error occurred while writing to it
```

5. Lastly, I too have made quite a lot of chat applications with Python (single channel but a lot more features), and when I started off I used HTTP requests via fetch as well, but that is extremely inefficient, so you should instead use websockets. [Flask-SocketIO](https://flask-socketio.readthedocs.io/en/latest/) is the best for this use case.

**Comment by gosoccerboy5** [comment]
im using github for version control

**Comment by gosoccerboy5** [comment]
interesting information, the context managers look a lot easier. however, im thinking of using an actual database like replit.db or sql

i'll have to look into websockets, thanks

**Comment by Chiroyce1** [comment]
> im using github for version control

yeah i know that, just add venv to the [gitignore](https://git-scm.com/docs/gitignore) so it isn't automatically pushed to github 

> interesting information, the context managers look a lot easier. however, im thinking of using an actual database like replit.db or sql

yeah that would be much better. if you're using repl db, remember that you wont be able to test locally, but that is the best choice for replit

> i'll have to look into websockets, thanks

😁

**Comment by Chiroyce1** [comment]
@gosoccerboy5 PLEASE ADD VENV TO GITIGNORE I CANT GO THROUGH THE DIFF PROPERLY AAAA

**Comment by gosoccerboy5** [comment]
i guess i finally finished this!! i can close the issue now
> @gosoccerboy5 PLEASE ADD VENV TO GITIGNORE I CANT GO THROUGH THE DIFF PROPERLY AAAA

🤓
